import Link from "next/link";
import { getAdminSubscriptionSnapshot } from "@/lib/billing/admin";
import { requireAdminSession } from "@/lib/admin-auth";

export default async function AdminSubscriptionsPage() {
  await requireAdminSession();
  const rows = await getAdminSubscriptionSnapshot();
  return <main className="min-h-screen bg-aviation-light p-5 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-aviation-accent">PLATFORM BILLING</p><h1 className="mt-1 text-3xl font-bold text-aviation-dark">Subscriptions</h1><p className="mt-1 text-sm text-aviation-muted">Operational view of trial status, paid plans and subscription state. Payment secrets remain server-side.</p></div><Link href="/admin/dashboard" className="min-h-11 rounded-xl border border-aviation-border bg-white px-4 py-2.5 text-sm font-semibold">Back to Admin</Link></div><section className="overflow-hidden rounded-2xl border border-aviation-border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-aviation-light"><tr><th className="px-5 py-4">Company</th><th className="px-5 py-4">Account</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Billing</th><th className="px-5 py-4">Period / Trial</th></tr></thead><tbody className="divide-y divide-aviation-border">{rows.map((row) => { if (!row) return null; const profile = row.profile as { company_name?: string|null; email?: string|null }|null; return <tr key={row.id}><td className="px-5 py-4"><p className="font-semibold text-aviation-dark">{profile?.company_name || "Unnamed company"}</p><p className="text-xs text-aviation-muted">{profile?.email || row.userId}</p></td><td className="px-5 py-4 capitalize">{row.accountType === "hybrid" ? "Buyer & Supplier" : "Buyer"}</td><td className="px-5 py-4 font-semibold">{row.planName}</td><td className="px-5 py-4"><span className="rounded-full bg-aviation-light px-2.5 py-1 text-xs font-semibold capitalize">{row.effectiveStatus.replaceAll("_", " ")}</span></td><td className="px-5 py-4">{row.billingInterval ?? "—"}</td><td className="px-5 py-4 text-xs text-aviation-muted">{row.trialEndsAt ? `Trial ends ${new Date(row.trialEndsAt).toLocaleDateString("en-GB")}` : row.currentPeriodEnd ? `Period ends ${new Date(row.currentPeriodEnd).toLocaleDateString("en-GB")}` : "—"}</td></tr>})}</tbody></table></div>{rows.length===0&&<p className="p-10 text-center text-sm text-aviation-muted">No subscription records found. Apply the Supabase billing migration to initialize the subscription tables.</p>}</section></div></main>;
}
