import Link from "next/link";
import { requireRole } from "@/lib/auth-guard";
import { requireActiveSubscription } from "@/lib/billing/subscription";
import { createClient } from "@/lib/supabase/server";

export default async function PromotionsPage() {
  await requireRole(["supplier"]); await requireActiveSubscription("promotions");
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser();
  const { data } = await supabase.from("promotions").select("id,title,description,discount,status,starts_at,ends_at,created_at").eq("supplier_id", user!.id).order("created_at", { ascending: false });
  return <main className="space-y-6"><header><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-aviation-accent">BRONZE SERVICE</p><h1 className="text-3xl font-bold text-aviation-dark">Promotions</h1><p className="mt-2 text-sm text-aviation-muted">Promotions require platform approval before becoming active.</p></header><section className="rounded-2xl border border-aviation-border bg-white p-5"><form action="/api/supplier/marketing/promotions" method="post" className="grid gap-4 md:grid-cols-2"><input name="title" required placeholder="Promotion title" className="min-h-11 rounded-xl border border-aviation-border px-3 text-sm"/><input name="discount" placeholder="Discount or offer" className="min-h-11 rounded-xl border border-aviation-border px-3 text-sm"/><textarea name="description" required placeholder="Describe the promotion" className="min-h-28 rounded-xl border border-aviation-border px-3 py-3 text-sm md:col-span-2"/><div className="md:col-span-2"><button className="min-h-11 rounded-xl bg-aviation-primary px-5 py-2.5 text-sm font-semibold text-white">Submit promotion</button></div></form></section><section className="space-y-3">{(data ?? []).map((row)=><article key={row.id} className="rounded-2xl border border-aviation-border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{row.title}</h2><span className="rounded-full bg-aviation-light px-3 py-1 text-xs font-semibold">{row.status}</span></div><p className="mt-2 text-sm text-aviation-muted">{row.description}</p>{row.discount&&<p className="mt-2 text-sm font-semibold">Offer: {row.discount}</p>}</article>)}{(data ?? []).length===0&&<p className="rounded-2xl border border-aviation-border bg-white p-8 text-center text-sm text-aviation-muted">No promotions submitted yet.</p>}</section><Link href="/supplier/marketing" className="inline-flex min-h-11 items-center text-sm font-semibold text-aviation-primary">Back to marketing</Link></main>;
}
