"use client";
import {useState} from "react";
import {SlidersHorizontal,X,Check} from "lucide-react";
import {usePathname,useRouter,useSearchParams} from "next/navigation";
import {MARKETPLACE_CATEGORIES,MARKETPLACE_CERTIFICATIONS,MARKETPLACE_CONDITIONS,marketplaceFilterCount} from "@/lib/marketplace-server";
const groups=["Condition","Certification","Category"] as const;
const keys={Condition:"condition",Certification:"certification",Category:"category"} as const;
function values(p:URLSearchParams,k:string){return p.getAll(k).flatMap(v=>v.split(",")).filter(Boolean)}
export default function MarketplaceSidebar({manufacturers,countries}:{manufacturers:string[];countries:string[]}){const router=useRouter(),pathname=usePathname(),params=useSearchParams();const [open,setOpen]=useState(false);const current={conditions:values(params,"condition"),certifications:values(params,"certification"),categories:values(params,"category"),manufacturers:values(params,"manufacturer"),countries:values(params,"country"),sort:"newest" as const};const count=marketplaceFilterCount(current);function update(k:string,v:string,checked:boolean){const p=new URLSearchParams(params.toString());const next=values(p,k).filter(x=>x!==v);if(checked)next.push(v);p.delete(k);next.forEach(x=>p.append(k,x));router.push(`${pathname}?${p.toString()}`,{scroll:false})}function clear(){router.push(pathname,{scroll:false})}function group(title:string,key:string,items:readonly string[]){return <section key={key} className="rounded-[var(--aviation-radius-lg)] border border-aviation-border bg-white p-4"><h3 className="mb-3 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-aviation-primary">{title}</h3>{items.map(item=>{const checked=values(params,key).includes(item);return <label key={item} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-md px-2 text-sm text-aviation-dark hover:bg-aviation-light"><input type="checkbox" checked={checked} onChange={e=>update(key,item,e.target.checked)} className="h-5 w-5 shrink-0 accent-[var(--aviation-primary)]"/><span>{item}</span></label>})}</section>}
const content=<div className="space-y-5">{groups.map(g=>group(g,keys[g],g==="Condition"?MARKETPLACE_CONDITIONS:g==="Certification"?MARKETPLACE_CERTIFICATIONS:MARKETPLACE_CATEGORIES))}{group("Manufacturer","manufacturer",manufacturers)}{group("Country / Region of Supplier","country",countries)}</div>;
return <><aside className="hidden lg:block lg:sticky lg:top-24"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-aviation-muted">Filter inventory</h2>{count>0&&<p className="mt-1 text-xs text-aviation-primary">{count} active filter{count===1?"":"s"}</p>}</div><button type="button" onClick={clear} disabled={!count} className="min-h-11 rounded-md px-3 text-xs font-semibold text-aviation-primary hover:bg-aviation-light disabled:opacity-40">Clear all</button></div>{content}</aside><div className="mb-5 lg:hidden"><button type="button" onClick={()=>setOpen(true)} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-[var(--aviation-radius-md)] border border-aviation-border bg-white px-4 text-sm font-semibold text-aviation-primary shadow-sm"><SlidersHorizontal size={18}/> Filters {count>0&&<span className="rounded-full bg-aviation-primary px-2 py-0.5 text-xs text-white">{count}</span>}</button></div>{open&&<div className="fixed inset-0 z-[70] lg:hidden" role="dialog" aria-modal="true" aria-label="Marketplace filters"><button aria-label="Close filters" className="absolute inset-0 h-full w-full bg-aviation-dark/45" onClick={()=>setOpen(false)}/><aside className="absolute inset-y-0 left-0 flex w-[min(88vw,380px)] flex-col bg-aviation-light shadow-xl"><div className="flex min-h-16 items-center justify-between border-b border-aviation-border bg-white px-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-aviation-muted">Marketplace</p><h2 className="font-semibold text-aviation-dark">Filters {count>0&&`(${count})`}</h2></div><button type="button" onClick={()=>setOpen(false)} className="inline-flex h-11 w-11 items-center justify-center rounded-md border border-aviation-border bg-white"><X size={20}/></button></div><div className="min-h-0 flex-1 overflow-y-auto p-4">{content}</div><div className="flex gap-2 border-t border-aviation-border bg-white p-4"><button onClick={clear} className="min-h-11 flex-1 rounded-[var(--aviation-radius-md)] border border-aviation-border px-4 font-semibold text-aviation-primary">Clear all</button><button onClick={()=>setOpen(false)} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-[var(--aviation-radius-md)] bg-aviation-primary px-4 font-semibold text-white"><Check size={17}/> Apply</button></div></aside></div>}</>}
