import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Part } from "@/lib/parts";

export const MARKETPLACE_CONDITIONS = ["New", "Serviceable", "Overhauled", "As Removed"] as const;
export const MARKETPLACE_CERTIFICATIONS = ["FAA 8130-3", "EASA Form 1", "Dual Release", "Certificate of Conformity", "OEM documentation", "Other", "None"] as const;
export const MARKETPLACE_CATEGORIES = ["Airframes", "Engines", "Avionics", "Components", "Landing Gear", "Consumables", "Electrical", "Safety Equipment"] as const;
export type MarketplaceSort = "newest" | "price-low" | "price-high" | "rating";
export interface MarketplaceFilters { conditions:string[]; certifications:string[]; categories:string[]; manufacturers:string[]; countries:string[]; sort:MarketplaceSort; query:string; }
export interface MarketplacePart extends Part { supplier_name:string; supplier_country:string|null; supplier_rating:number|null; supplier_verification_status:string; supplier_verification_completion:number; verified_certification_types?:string[]; }
export function getPublicSupabase():SupabaseClient { const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if(!url||!key) throw new Error("Supabase public environment variables are not configured."); return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}); }
function cleanList(values:string[]|undefined, allowed?:readonly string[]){const cleaned=[...new Set((values??[]).map(v=>v.trim()).filter(Boolean))]; return allowed?cleaned.filter(v=>allowed.includes(v)):cleaned;}
export function normalizeMarketplaceFilters(input:Partial<MarketplaceFilters>={}):MarketplaceFilters { const sort=input.sort&&["newest","price-low","price-high","rating"].includes(input.sort)?input.sort:"newest"; return {conditions:cleanList(input.conditions,MARKETPLACE_CONDITIONS),certifications:cleanList(input.certifications,MARKETPLACE_CERTIFICATIONS),categories:cleanList(input.categories,MARKETPLACE_CATEGORIES),manufacturers:cleanList(input.manufacturers),countries:cleanList(input.countries),sort,query:(input as Partial<MarketplaceFilters>).query?.trim()||""}; }
export function parseMarketplaceSearchParams(searchParams:Record<string,string|string[]|undefined>):MarketplaceFilters { const list=(key:string)=>{const v=searchParams[key]; return Array.isArray(v)?v.flatMap(x=>x.split(",")):(v?v.split(","):[])}; return normalizeMarketplaceFilters({conditions:list("condition"),certifications:list("certification"),categories:list("category"),manufacturers:list("manufacturer"),countries:list("country"),sort:(Array.isArray(searchParams.sort)?searchParams.sort[0]:searchParams.sort) as MarketplaceSort|undefined,query:Array.isArray(searchParams.q)?searchParams.q[0]:(searchParams.q||"")}); }
export function marketplaceFilterCount(f:MarketplaceFilters){return f.conditions.length+f.certifications.length+f.categories.length+f.manufacturers.length+f.countries.length;}
function certificationLabel(value:string|null){const n=(value??"").trim().toLowerCase(); if(n.includes("faa")||n.includes("8130")) return "FAA 8130-3"; if(n.includes("easa")||n.includes("form 1")) return "EASA Form 1"; if(n.includes("dual")) return "Dual Release"; if(n.includes("conformity")) return "Certificate of Conformity"; if(n.includes("oem")) return "OEM documentation"; if(n && n !== "none") return "Other"; return "None";}

async function getVerifiedCertificationMap(supabase:SupabaseClient, partIds:string[]){
  if(!partIds.length) return new Map<string,string[]>();
  const {data,error}=await supabase.rpc("get_public_part_verified_certifications",{p_part_ids:partIds});
  if(error){console.error("GET VERIFIED LISTING CERTIFICATIONS ERROR:",{message:error?.message,details:error?.details,hint:error?.hint,code:error?.code}); return new Map<string,string[]>();}
  const map=new Map<string,string[]>();
  for(const row of data??[]){const list=map.get(row.part_id)??[]; if(!list.includes(row.document_type)) list.push(row.document_type); map.set(row.part_id,list);}
  return map;
}

export async function getMarketplacePartsForSeo(limit=24, filters?:Partial<MarketplaceFilters>):Promise<MarketplacePart[]> { try { const supabase=getPublicSupabase(); const f=normalizeMarketplaceFilters(filters); let query=supabase.from("parts").select("*").eq("status","Published"); if(f.conditions.length) query=query.in("condition",f.conditions); if(f.categories.length) query=query.in("category",f.categories); if(f.manufacturers.length) query=query.in("manufacturer",f.manufacturers); if(f.query){const q=f.query.replace(/,/g," ").replace(/%/g,"").replace(/_/g,""); const nsnProbe=await supabase.from("parts").select("nsn").limit(1); const nsnClause=!nsnProbe.error?`,nsn.ilike.%${q}%`:""; query=query.or(`part_number.ilike.%${q}%,manufacturer.ilike.%${q}%,description.ilike.%${q}%,alternate_part_number.ilike.%${q}%${nsnClause}`);} if(f.sort==="price-low") query=query.order("unit_price",{ascending:true}); else if(f.sort==="price-high") query=query.order("unit_price",{ascending:false}); else query=query.order("created_at",{ascending:false}); const {data:parts,error}=await query.limit(500); if(error) throw error; const rows=(parts??[]) as Part[]; const verifiedCertificationMap=await getVerifiedCertificationMap(supabase, rows.map(p=>p.id)); const ids=[...new Set(rows.map(p=>p.supplier_id).filter(Boolean))]; const supplierMap=new Map<string,{name:string;country:string|null;rating:number|null;verification_status:string;verification_completion:number}>(); if(ids.length){const [{data:suppliers},{data:profiles}]=await Promise.all([supabase.from("suppliers").select("id, company_name, verification_status, verification_completion").in("id",ids),supabase.from("profiles").select("id,country").in("id",ids)]); const pm=new Map((profiles??[]).map(p=>[p.id,p])); for(const s of suppliers??[]) supplierMap.set(s.id,{name:s.company_name||"Verified Supplier",country:pm.get(s.id)?.country??null,rating:null,verification_status:s.verification_status||"Draft",verification_completion:Number(s.verification_completion||0)});} let mapped=rows.map(p=>({...p,supplier_name:supplierMap.get(p.supplier_id)?.name||"Verified Supplier",supplier_country:supplierMap.get(p.supplier_id)?.country??null,supplier_rating:supplierMap.get(p.supplier_id)?.rating??null,supplier_verification_status:supplierMap.get(p.supplier_id)?.verification_status||"Draft",supplier_verification_completion:supplierMap.get(p.supplier_id)?.verification_completion??0,verified_certification_types:verifiedCertificationMap.get(p.id)??[]})); if(f.certifications.length) mapped=mapped.filter(p=>{const types=p.verified_certification_types??[]; return f.certifications.includes("None") ? (types.length===0 || types.some(t=>f.certifications.includes(t))) : types.some(t=>f.certifications.includes(t));}); if(f.countries.length) mapped=mapped.filter(p=>f.countries.includes(p.supplier_country||""));
 const supplierIds=[...new Set(mapped.map(p=>p.supplier_id).filter(Boolean))];
 const boostMap=new Map<string,number>();
 if(supplierIds.length){ const {data:boostRows}=await supabase.rpc("marketplace_supplier_search_boosts",{p_supplier_ids:supplierIds}); for(const row of boostRows??[]) boostMap.set(row.supplier_id,Number(row.boost)||0); }
 if(f.sort==="rating") mapped.sort((a,b)=>(b.supplier_rating??-1)-(a.supplier_rating??-1));
 else if(!f.sort || f.sort==="newest") mapped.sort((a,b)=>(boostMap.get(b.supplier_id)||0)-(boostMap.get(a.supplier_id)||0) || (new Date(b.created_at??0).getTime()-new Date(a.created_at??0).getTime()));
 return mapped.slice(0,limit); } catch(error){console.error("GET SEO MARKETPLACE PARTS ERROR:",{message:error instanceof Error?error.message:"Unknown error",details:(error as any)?.details,hint:(error as any)?.hint,code:(error as any)?.code}); return [];} }
export async function getMarketplaceFacetOptions(){try{const supabase=getPublicSupabase(); const [{data:parts},{data:profiles}]=await Promise.all([supabase.from("parts").select("manufacturer,category,condition,trace_certificate,supplier_id").eq("status","Published").limit(1000),supabase.from("profiles").select("id,country").limit(1000)]); const pm=new Map((profiles??[]).map(p=>[p.id,p.country])); return {manufacturers:[...new Set((parts??[]).map(p=>p.manufacturer).filter(Boolean) as string[])].sort(),countries:[...new Set((parts??[]).map(p=>pm.get(p.supplier_id)).filter(Boolean) as string[])].sort()};}catch(error){console.error("GET MARKETPLACE FACETS ERROR:",{message:error instanceof Error?error.message:"Unknown error",details:(error as any)?.details,hint:(error as any)?.hint,code:(error as any)?.code});return {manufacturers:[],countries:[]};}}
export async function getPublicMarketplacePartById(id:string):Promise<MarketplacePart|null>{if(!id)return null;try{const supabase=getPublicSupabase();const {data:part,error}=await supabase.from("parts").select("*").eq("id",id).eq("status","Published").maybeSingle();if(error)throw error;if(!part)return null;const [{data:supplier},{data:profile},verifiedCertificationMap]=await Promise.all([supabase.from("suppliers").select("company_name, verification_status, verification_completion").eq("id",part.supplier_id).maybeSingle(),supabase.from("profiles").select("country").eq("id",part.supplier_id).maybeSingle(),getVerifiedCertificationMap(supabase,[part.id])]);return {...(part as Part),supplier_name:supplier?.company_name||"Verified Supplier",supplier_country:profile?.country??null,supplier_rating:null,supplier_verification_status:supplier?.verification_status||"Draft",supplier_verification_completion:Number(supplier?.verification_completion||0),verified_certification_types:verifiedCertificationMap.get(part.id)??[]};}catch(error){console.error("GET PUBLIC MARKETPLACE PART ERROR:",{message:error instanceof Error?error.message:"Unknown error",details:(error as any)?.details,hint:(error as any)?.hint,code:(error as any)?.code});return null;}}
