import Link from "next/link";
import { requireRole } from "@/lib/auth-guard";
import { requireActiveSubscription } from "@/lib/billing/subscription";
import { createClient } from "@/lib/supabase/server";

export default async function CampaignsPage({ searchParams }: { searchParams: Promise<{ type?: string }> }) {
  await requireRole(["supplier"]); const subscription = await requireActiveSubscription(); const params = await searchParams; const type = params.type === "newsletter" || params.type === "whatsapp" || params.type === "external_advertising" ? params.type : "external_advertising";
  const required = type === "external_advertising" ? "external_advertising" : type === "newsletter" ? "newsletter_promotion" : "whatsapp_promotion"; if (!subscription.entitlements.includes(required)) return <main className="rounded-2xl border border-aviation-border bg-white p-8"><h1 className="text-2xl font-bold">Platinum service required</h1><p className="mt-2 text-sm text-aviation-muted">This marketing request is available with Platinum.</p><Link href="/account/subscription" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-aviation-primary px-4 text-sm font-semibold text-white">View subscription</Link></main>;
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const { data } = await supabase.from("marketing_requests").select("id,request_type,status,campaign_objective,target_audience,promotional_content,starts_at,ends_at,created_at").eq("supplier_id", user!.id).eq("request_type", type).order("created_at", { ascending: false });
  return <main className="space-y-6"><header><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-aviation-accent">PLATINUM SERVICE</p><h1 className="text-3xl font-bold text-aviation-dark">{type === "external_advertising" ? "External Advertising" : type === "newsletter" ? "Newsletter Promotion" : "WhatsApp Promotion"}</h1><p className="mt-2 text-sm text-aviation-muted">Submit a campaign request for platform review. No campaign is represented as sent or active until the corresponding service actually runs.</p></header><section className="rounded-2xl border border-aviation-border bg-white p-5"><form action="/api/supplier/marketing/campaigns" method="post" className="grid gap-4 md:grid-cols-2"><input type="hidden" name="requestType" value={type}/><textarea name="campaignObjective" required placeholder="Campaign objective" className="min-h-24 rounded-xl border border-aviation-border px-3 py-3 text-sm"/><textarea name="targetAudience" required placeholder="Target audience" className="min-h-24 rounded-xl border border-aviation-border px-3 py-3 text-sm"/><textarea name="promotionalContent" required placeholder="Promotional content" className="min-h-28 rounded-xl border border-aviation-border px-3 py-3 text-sm md:col-span-2"/><div><label className="text-xs font-semibold">Start date</label><input type="date" name="startsAt" className="mt-1 min-h-11 w-full rounded-xl border border-aviation-border px-3 text-sm"/></div><div><label className="text-xs font-semibold">End date</label><input type="date" name="endsAt" className="mt-1 min-h-11 w-full rounded-xl border border-aviation-border px-3 text-sm"/></div><div className="md:col-span-2"><button className="min-h-11 rounded-xl bg-aviation-primary px-5 py-2.5 text-sm font-semibold text-white">Submit request</button></div></form></section><section className="space-y-3">{(data ?? []).map((row)=><article key={row.id} className="rounded-2xl border border-aviation-border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">Request #{row.id.slice(0,8).toUpperCase()}</h2><span className="rounded-full bg-aviation-light px-3 py-1 text-xs font-semibold">{row.status}</span></div><p className="mt-2 text-sm text-aviation-muted">{row.campaign_objective}</p></article>)}</section><Link href="/supplier/marketing" className="inline-flex min-h-11 items-center text-sm font-semibold text-aviation-primary">Back to marketing</Link></main>;
}
