"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import { AlertTriangle, ArrowLeft, CheckCircle2, ClipboardCheck, FileText, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { getSupplierVerification, submitSupplierVerification, type SupplierVerificationDocument, type SupplierVerificationSummary } from "@/lib/supplier-verification";
import VerificationStatusBadge from "@/components/supplier/verification/VerificationStatusBadge";
import DocumentManager from "@/components/supplier/verification/DocumentManager";
import VerificationChecklist from "@/components/supplier/verification/VerificationChecklist";

export default function SupplierVerificationPage() {
  const [supplierId,setSupplierId]=useState<string|null>(null); const [company,setCompany]=useState(""); const [supplier,setSupplier]=useState<{company_name:string|null;business_type:string|null;website:string|null;address:string|null;city:string|null}>({company_name:null,business_type:null,website:null,address:null,city:null}); const [profile,setProfile]=useState<{full_name:string|null;email:string|null;phone:string|null;registration_number:string|null;onboarding_data:Record<string,unknown>|null}|null>(null); const [summary,setSummary]=useState<SupplierVerificationSummary|null>(null); const [documents,setDocuments]=useState<SupplierVerificationDocument[]>([]); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{(async()=>{try{const {data:{user}}=await supabase.auth.getUser();if(!user) return;setSupplierId(user.id);const result=await getSupplierVerification(user.id);setCompany(result.supplier.company_name || "Supplier");setSupplier({company_name:result.supplier.company_name,business_type:result.supplier.business_type,address:result.supplier.address,city:result.supplier.city,website:result.supplier.website});setDocuments(result.documents);setProfile(result.profile);setSummary(result.summary || {verification_status:result.supplier.verification_status,verification_completion:result.supplier.verification_completion,verification_comments:result.supplier.verification_comments,verification_missing_information:result.supplier.verification_missing_information || [],document_count:result.documents.length,verified_document_count:result.documents.filter(d=>d.verification_status==="Verified").length,expiring_document_count:0,expired_document_count:0});}catch(e){toast.error(e instanceof Error?e.message:"Unable to load verification center.")}finally{setLoading(false)}})()},[]);
  async function submit(){setSubmitting(true);try{await submitSupplierVerification();toast.success("Verification submitted for AviaInventory review.");if(supplierId){const result=await getSupplierVerification(supplierId);setSummary(result.summary);setCompany(result.supplier.company_name||company);}}catch(e){toast.error(e instanceof Error?e.message:"Unable to submit verification.")}finally{setSubmitting(false)}}
  if(loading)return <div className="space-y-5"><div className="skeleton h-40 rounded-2xl"/><div className="skeleton h-24 rounded-2xl"/><div className="skeleton h-96 rounded-2xl"/></div>;
  if(!summary||!supplierId)return <div className="rounded-2xl bg-white p-8 text-center"><h1 className="text-xl font-bold">Supplier verification unavailable</h1><p className="mt-2 text-sm text-aviation-muted">Create or activate your supplier profile before starting verification.</p></div>;
  const canSubmit=["Draft","More Information Required","Rejected"].includes(summary.verification_status);
  return <div className="space-y-6">
    <Link href="/supplier/dashboard" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-aviation-primary"><ArrowLeft size={16}/> Back to supplier workspace</Link>
    <section className="rounded-[var(--aviation-radius-xl)] border border-aviation-border bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-aviation-accent">AVIATION COMPLIANCE</p><h1 className="mt-1 text-2xl font-bold text-aviation-dark sm:text-3xl">Supplier Verification Center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-aviation-muted">Prepare your company credentials, aviation approvals and controlled documents for AviaInventory review.</p></div><VerificationStatusBadge status={summary.verification_status}/></div><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto]"><div><div className="flex items-center justify-between text-sm"><span className="font-semibold">Profile completion</span><span className="font-mono font-bold text-aviation-primary">{summary.verification_completion}%</span></div><div className="mt-2 h-2.5 rounded-full bg-aviation-light"><div className="h-full rounded-full bg-aviation-accent" style={{width:`${summary.verification_completion}%`}}/></div></div>{canSubmit&&<button disabled={submitting} onClick={submit} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-aviation-accent px-5 py-3 text-sm font-semibold text-white disabled:opacity-60"><ClipboardCheck size={17}/>{submitting?"Submitting…":"Submit for verification"}</button>}</div></section>
    <VerificationChecklist profile={profile} supplier={supplier} documents={documents}/>
    <section className="grid gap-4 md:grid-cols-3"><Metric icon={ShieldCheck} label="Verified documents" value={summary.verified_document_count} hint={`${summary.document_count} active documents`} /><Metric icon={AlertTriangle} label="Expiry watch" value={summary.expiring_document_count} hint="Next 30 days" danger={summary.expiring_document_count>0}/><Metric icon={FileText} label="Expired" value={summary.expired_document_count} hint="Replacement required" danger={summary.expired_document_count>0}/></section>
    {(summary.verification_comments || summary.verification_missing_information.length>0) && <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-aviation-primary/15 bg-aviation-primary/5 p-5"><div className="flex gap-3"><CheckCircle2 className="shrink-0 text-aviation-primary" size={20}/><div><h2 className="font-bold text-aviation-dark">Verification comments</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-aviation-muted">{summary.verification_comments || "No reviewer comments have been added."}</p></div></div></div><div className="rounded-xl border border-aviation-warning/20 bg-aviation-warning-soft p-5"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-aviation-warning" size={20}/><div><h2 className="font-bold text-aviation-dark">Missing information / actions required</h2>{summary.verification_missing_information.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-aviation-muted">{summary.verification_missing_information.map(item=><li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-aviation-muted">No outstanding items have been identified.</p>}</div></div></div></section>}
    <DocumentManager supplierId={supplierId} initialDocuments={documents}/>
    <section className="rounded-xl border border-aviation-border bg-aviation-light p-5"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-aviation-primary" size={21}/><div><h2 className="font-bold text-aviation-dark">What buyers can see</h2><p className="mt-1 text-sm leading-6 text-aviation-muted">Public supplier cards, marketplace listings and supplier profiles display the supplier verification status only. Private compliance files, reviewer notes and expiry metadata remain inside the controlled verification workspace.</p></div></div></section>
  </div>;
}
function Metric({icon:Icon,label,value,hint,danger=false}:{icon:typeof ShieldCheck;label:string;value:number;hint:string;danger?:boolean}){return <div className="rounded-xl border border-aviation-border bg-white p-5"><div className="flex items-center justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-lg ${danger?"bg-red-50 text-red-700":"bg-aviation-light text-aviation-primary"}`}><Icon size={19}/></div><span className={`font-mono text-2xl font-bold ${danger?"text-red-700":"text-aviation-primary"}`}>{value}</span></div><p className="mt-4 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-aviation-muted">{hint}</p></div>}
